### ISSUE TITLE
Get Virtual Environment to work

### ISSUE THREAD

**Issue by CoffeeCodeRpt** [CoffeeCodeRpt/pythonFlappyBird#8]
Virtual environment isn't showing that Pygame is available even though it's installed and I need to figure that out. 

Going to look at the [Official Docs](https://docs.python.org/3/tutorial/venv.html?highlight=virtual%20environment)

**Comment by CoffeeCodeRpt** [comment]
fixed this with a direct push to main but didn't really need to as it's a feature in VSCode. New environment folder is `.venv`

**Comment by Rishikesh-kumar-7258** [comment]
In virtual environment you actually have to download pygame again.
Use pip install pyagme
